version: '3'
# Each package in the mono repo only starts the docker services that it needs
# for testing using the "pretest" npm command.
services:
  node:
    image: ghcr.io/meshx-org/sidetree-node:sha-29aa29e
    restart: always
    ports:
      - '3000:3000'
    environment:
      - PORT=3000
      - MONGO_URL=mongodb://mongo:27017/
  
  mongo:
    image: mongo
    restart: always
    ports:
      - '27017:27017'
