name: Build and Push Service

on:
  workflow_call:
    inputs:
      service_name:
        required: true
        type: string
      service_tag:
        required: true
        type: string
      service_description:
        required: true
        type: string
      registry_username:
        required: true
        type: string
    secrets:
      GHPR_TOKEN:
        required: true

jobs:
  build-push-service:
    name: Build and Push Service
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Collect Docker metadata
        id: docker_meta
        uses: docker/metadata-action@v3
        with:
          images: ghcr.io/${{ inputs.registry_username }}/${{ inputs.service_tag }}
          tags: |
            type=edge,branch=main
            type=semver,pattern={{version}}
            type=sha,enable=true,priority=100,prefix=sha-,suffix=,format=short
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ inputs.registry_username }}
          password: ${{ secrets.GHPR_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          build-args: |
            SERVICE=${{ inputs.service_name }}
          cache-from: type=gha, scope=${{ github.workflow }}
          cache-to: type=gha, scope=${{ github.workflow }}
          push: true
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: |
            ${{ steps.docker_meta.outputs.labels }}
            org.opencontainers.image.vendor=MeshX
            org.opencontainers.image.title=${{ inputs.service_name }}
            org.opencontainers.image.description=${{ inputs.service_description }}
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
        shell: bash
